### ISSUE TITLE
It doesn`t work for d3 last version, and for all d3 version higher then 3

### ISSUE THREAD

**Issue by artem-kushal** [NPashaP/Viz#1]
![2016-07-11_1536](https://cloud.githubusercontent.com/assets/13419905/16730740/540440ba-477d-11e6-8b66-9c2a8c24cb14.png)
I get this error for d3 3.4.13 version.

**Comment by NPashaP** [comment]
Is this for biPartite? It should work with d3js.org/d3.v3.min.js (3.5.17 at the moment).

Working with d3.v4 I noticed that the d3.nest returns objects with values attribute and d3.v3 returns an object with value attribute.  This is causing an error with all v4 versions. Will have to find out why it was changed.

**Comment by NPashaP** [comment]
I created a new version which should work with d3.v4. It is at http://vizjs.org/viz.v1.0.3.min.js

**Comment by artem-kushal** [comment]
Now, its work fine. Thanks.
