### ISSUE TITLE
Remove sort on labels

### ISSUE THREAD

**Issue by kulfy** [NPashaP/Viz#10]
This is more of question than an actual issue. One of the columns on my bP is a date (MMM-YY, JAN-16 and such). Is there a way to unsort the labels so the order shows up chronologically (because it's a date) and not alphabetically?

**Comment by NPashaP** [comment]
You could use the bP.sortPrimary and bP.sortSecondary methods to specify a sorting function that uses date format. This example demonstrates these methods: http://bl.ocks.org/NPashaP/d61e36d237bca061125bac66d86026d3

**Comment by kulfy** [comment]
Thanks, works perfectly, that is exactly what I was looking for.

**Comment by mjhoefer** [comment]
@kulfy @NPashaP this link is dead. Would you be willing to re-share this example?

http://bl.ocks.org/NPashaP/d61e36d237bca061125bac66d86026d3

I'm looking to sort by value. I'm thinking I need to make a lookup dict with keys being the labels, as I'm not sure how to access the values inside the sort function (passed as sortPrimary/sortSecondary).

Many thanks in advance.

**Comment by mjhoefer** [comment]
Please disregard, it was pretty simple to do something like this:
```

var need_order = {
				Subsistence:0, 
				Protection:1, 
				Affection:2, 
				Understanding:3, 
				Participation:4, 
				Leisure:5, 
				Creation:6, 
				Identity:7, 
				Freedom:8, 
				Spirituality:9, 
				None:10};

function sortByNeedOrder(a, b) {
				return need_order[a] - need_order[b];
			}
```

Then pass in sortByNeedOrder to sortPrimary when chaining the bP call. 

PS thank you for this awesome library.
