### ISSUE TITLE
Labels hidden or overlapping on big datasets

### ISSUE THREAD

**Issue by yianni-ververis** [NPashaP/Viz#17]
Hello,

It seems that if there are a lot of labels, they do overlap. I tried to play with svg height and height() but the results are either hidden or overlapping.

![2017-09-26 10_24_38](https://user-images.githubusercontent.com/12610095/30865647-35abdb4e-a2a5-11e7-8615-d3cfa34e037b.png)

**Comment by NPashaP** [comment]
If there is not enough total height then the labels will end up overlapping. You can increase the height of the viz (see http://bl.ocks.org/NPashaP/aeef4383faf3a5885d95799e4cfdd220) to have enough room. You could also hide labels which have a value less than a threshold.

**Comment by yianni-ververis** [comment]
I gave it 
svg.attr("height", vars.canvasHeight);
var g = svg.append("g").attr("transform", "translate(150,30)");
.height(vars.canvasHeight-30)

where canvasHeight is even 4000 with the same results

**Comment by NPashaP** [comment]
viz.bP() has its own height function.
