### ISSUE TITLE
Runtime ordering nodes in biPartite

### ISSUE THREAD

**Issue by vusan** [NPashaP/Viz#2]
With `.sortPrimary()` it works fine initially but on runtime (on mouse hover) it won't work but `.sortPrimary()` would called.

**Comment by NPashaP** [comment]
I am not sure I follow the issue. 
Here is an example focused on sortPrimary which seem to be working fine as is and on hover.  http://bl.ocks.org/NPashaP/d61e36d237bca061125bac66d86026d3

Could you explain the issue using that example?

**Comment by vusan** [comment]
Thanks for quick reply.
After just page refreshed, the primary nodes are sorted as B,C,A. And after hovering on the secondary node('X','Y') , the primary nodes will be shown as B,C,A. So working fine.

Now while hovering on 'X', I want to sort primary nodes as A,B,C.

What I do is just changing 
`bca=["A","B","C"];` just after `bP.mouseover = function(d)` 

But the ordering of primary nodes is always B,C,A.
In anyway can we reorder B,C,A to A,B,C without refresh ?

**Comment by NPashaP** [comment]
Right now if you change sort order, you will have to refresh. Since the sort order affects both parts, changing it will relocate the hovered node itself.
