### ISSUE TITLE
Using new data

### ISSUE THREAD

**Issue by kafom** [NPashaP/Viz#3]
NPasha great visualization. 
How does one update the data. For instance, if I wanted to have the viz change for different years selected?
Thanks

**Comment by NPashaP** [comment]
It is on my todo list to have a function to refresh data.

For now, for the biPartite, you can use the bP.bars() function to get objects needed to redraw.

**Comment by NPashaP** [comment]
I added an `update` method to bP. 

Here is an example [bP.update](http://bl.ocks.org/npashap/2684287c2526c837b04ce873901c918d)
