### ISSUE TITLE
d.value doesn't work

### ISSUE THREAD

**Issue by cosfo** [NPashaP/Viz#4]
Hi.
Thank you for your amazing project.
I found an issue.

I try to use d.value, but d.value is undefined value.
I confirmed source code. LINE 184 ",value:d.value" should be ",value:d.values" .

**Comment by NPashaP** [comment]
It is happening due to a change to d3.nest from d3.v3 to d3.v4. If you are using d3.v4 then please use http://vizjs.org/viz.v1.0.3.min.js

Hope that fixes your issue.
