### ISSUE TITLE
Update doesn't work properly

### ISSUE THREAD

**Issue by kafom** [NPashaP/Viz#5]
Pasha, 
Thanks for adding the update.
However it only works when the data changes but not the number of connections. 

See the example below. 
As shown when you run the program, the edges do not update correctly. 

<!DOCTYPE html>
<meta charset="utf-8">

<style>
    .mainBars{
        shape-rendering: auto;
        fill-opacity: 0;
        stroke-width: 0.5px;
        stroke: rgb(0, 0, 0);
        stroke-opacity: 0;
    }
    .subBars{
        shape-rendering:crispEdges;
    }
    .edges{
        stroke:none;
        fill-opacity:0.3;
    }
</style>

<body>

<script src="https://d3js.org/d3.v4.min.js"></script>

<script src="http://vizjs.org/viz.v1.1.1.min.js"></script>

<script>
    var data={
        1:[['A','X', 1]
        ,['A','Y', 3]
        ,['B','X', 5]
        ,['B','Y', 8]
        ,['C','X', 2]
        ,['C','Y', 9]
    ],
        2:[['A','X', 5]
            ,['A','Y', 3]
            ,['B','X', 10]
            ,['B','Y', 8]
            ,['C','X', 2]
            ,['C','Y', 1]
        ],
        3:[['A','X', 10]
            ,['B','X', 15]
            ,['B','Y', 8]
            ,['C','X', 2]
            ,['C','Y', 9]
        ],
        4:[['A','X', 1]
            ,['A','Y', 3]
            ,['B','X', 5]
            ,['B','Y', 4]
            ,['C','X', 2]
            ,['C','Y', 9]
            ,['D','X', 19]
            ,['D','Y', 4]
        ],
        5:[['A','X', 10]
            ,['A','Y', 13]
            ,['B','X', 5]
            ,['B','Y', 18]
            ,['C','X', 21]
            ,['C','Y', 9]
        ]
    };

    var width=960, height=700;
    var color = {A:"#3366CC", B:"#DC3912",  C:"#FF9900"};

    //create bp object
    var i = 1;
    var bp=viz.bP().data(data[i]).pad(2).fill(d=>color[d.primary]);

    // create svg and g elements and draw bp on it
    d3.select("body").append("svg").attr("width", width).attr("height", height)
            .append("g").attr("transform","translate(250,50)").call(bp);

    // refresh data every second
    setInterval(update,5000);

    function update(){
        console.log(data[i])
        i = i+1;
        // reate some random values
     //   data.forEach(function(d){ d[2] =Math.random()*10 ;});
        //set the new data and redraw
        if (i < 5)
            bp.update(data[i]);
        else
                i = 0;
    }

    // adjust the bl.ocks frame dimension.
    d3.select(self.frameElement).style("height", height+"px").style("width", width+"px");
</script>

</body>
</html>

**Comment by NPashaP** [comment]
The update is designed for when the values change and not the groups. 

I will look into adding exit and enter for new groups in the update. I am not sure what kind of transition they should have, I will have to figure those out.

**Comment by nightire** [comment]
@NPashaP So any progress on groups exit and/or enter?

Is there an alternative way to update whole chart? I'm thinking maybe I can destroy it entirely then redrawing, but I can't find how to destroy it...
