### ISSUE TITLE
How to add custom fields?

### ISSUE THREAD

**Issue by ubaid-rehman** [NPashaP/Viz#7]
I am using d3 v4. Drawing biPartite - Adding labels Example [URL TO Example](http://bl.ocks.org/NPashaP/3ba0031d3d555afca4713e5264455025)
My sample data is 
`var data = [
                ['host1', 'Call 1', 524, 'Kb'],
                ['host2', 'Call 2', 56, 'Kb'],
                ];`
I want this 4th element accessible in a variable e.g "unit"

So far I have declared unit like this

`var key_scale, value_scale
        ,keyPrimary, keySecondary, value, unit
        ,width, height, orient, barSize, min, pad
        ,data, fill, g, edgeOpacity, duration
        ,sortPrimary, sortSecondary, edgeMode
      ;`

added a function in viz.bP like this

`bP.unit = function(_){ 
          if(!arguments.length) return typeof unit !== "undefined" ? unit : function(d){ return d[3]; };
          value = _;
          return bP;    
      }`

But it is not accessible like other variables like d.part, d.percent, d.value and d.key

I tried to add it into calculateMainBars() function as a key value pair like this

`       function calculateMainBars(part){

```
        function v(d){ return isSelKey(d, part) ? bP.value()(d): 0;};

        var ps = d3.nest()
            .key(part=="primary"? bP.keyPrimary():bP.keySecondary())
            .sortKeys(part=="primary"? bP.sortPrimary():bP.sortSecondary())
            .rollup(function(d){ return d3.sum(d,v); })
            .entries(bP.data());

        var bars = bpmap(ps, bP.pad(), bP.min(), 0, _or=="vertical" ? bP.height() : bP.width());
        var bsize = bP.barSize();
        ps.forEach(function(d,i){
            mainBars[part].push({
                 x:_or=="horizontal"? (bars[i].s+bars[i].e)/2 : (part=="primary" ? bsize/2 : bP.width()-bsize/2)
                ,y:_or=="vertical"? (bars[i].s+bars[i].e)/2 : (part=="primary" ? bsize/2 : bP.height()-bsize/2)
                ,height:_or=="vertical"? (bars[i].e - bars[i].s)/2 : bsize/2
                ,width: _or=="horizontal"? (bars[i].e - bars[i].s)/2 : bsize/2
                ,part:part
                ,key:d.key
                ,unit:d.unit
                ,value:d.value
                ,percent:bars[i].p
            });
        });
    }`
```

but it is not accessible here.

I know I am missing something very basic but please help me out :)

**Comment by NPashaP** [comment]
The d3.nest().rollup removes the original data and keeps only the keys and aggregated values. 
Examples:
`d3.nest().key(d=> d[0]).entries([["A",1,"z"],["B",2,"z"]])`

`d3.nest().key(d=> d[0]).rollup(d=>d3.sum(d,t=>t[1])).entries([["A",1,"z"],["B",2,"z"]])`

A solution could be to replace the nesting step with your own nesting method which keeps the 4th element and then grab it and pass it as a key value in the push step.

**Comment by ubaid-rehman** [comment]
Thanks NPashaP for your help.
