### ISSUE TITLE
Question about http://bl.ocks.org/NPashaP/9994181

### ISSUE THREAD

**Issue by eumesmoson** [NPashaP/Viz#9]
Hi:
In your example in: http://bl.ocks.org/NPashaP/9994181 . 
What is the type of license?
Can I use it in a GPL proyect? 
http://xinzodelimia.esy.es/nova/economia.php
Regards :)

**Comment by NPashaP** [comment]
I have added a license to it. Feel free to use it.

**Comment by eumesmoson** [comment]
Thank you very much
Regards :)
